"""initial schema with indexes and numeric types

Revision ID: 839588efecf2
Revises: 
Create Date: 2026-04-10 19:09:40.662987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839588efecf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_split', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_bill_split_debtor_id'), ['debtor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_split_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_split_payer_id'), ['payer_id'], unique=False)

    with op.batch_alter_table('category_budget', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_category_budget_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_expense_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('monthly_income',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monthly_target',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_profile_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_username'))
        batch_op.alter_column('monthly_target',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monthly_income',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_user_id'))
        batch_op.drop_index(batch_op.f('ix_expense_date'))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('category_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_budget_user_id'))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('bill_split', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_split_payer_id'))
        batch_op.drop_index(batch_op.f('ix_bill_split_expense_id'))
        batch_op.drop_index(batch_op.f('ix_bill_split_debtor_id'))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
